# Generated by Django 5.1.3 on 2024-11-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="proDb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Catgories", models.CharField(blank=True, max_length=200, null=True)),
                ("Products", models.CharField(blank=True, max_length=200, null=True)),
                ("Price", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "Description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "ProductImage",
                    models.ImageField(
                        blank=True, null=True, upload_to="product Images"
                    ),
                ),
            ],
        ),
    ]
