# Generated by Django 5.1.3 on 2024-11-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WebApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactdb",
            name="CustomerSubject",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
