# Generated by Django 5.1.3 on 2024-11-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WebApp", "0002_contactdb_customersubject"),
    ]

    operations = [
        migrations.CreateModel(
            name="userDb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Username", models.CharField(blank=True, max_length=200, null=True)),
                ("Usermobile", models.CharField(blank=True, max_length=200, null=True)),
                ("Useremail", models.EmailField(blank=True, max_length=200, null=True)),
                ("Password", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "ConfirmPass",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
    ]
