# Generated by Django 5.1.3 on 2024-12-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WebApp", "0004_cartdb"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderDb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(blank=True, max_length=200, null=True)),
                ("Email", models.EmailField(blank=True, max_length=200, null=True)),
                ("Place", models.CharField(blank=True, max_length=200, null=True)),
                ("Address", models.CharField(blank=True, max_length=200, null=True)),
                ("Mobile", models.CharField(blank=True, max_length=200, null=True)),
                ("State", models.CharField(blank=True, max_length=200, null=True)),
                ("Pin", models.IntegerField(blank=True, max_length=200, null=True)),
                (
                    "TotalPrice",
                    models.IntegerField(blank=True, max_length=200, null=True),
                ),
                ("Message", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
