# Generated by Django 5.1.3 on 2024-12-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WebApp", "0005_orderdb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdb",
            name="Pin",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderdb",
            name="TotalPrice",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
